
version: "3.7"
services:

  reverse_proxy:
    image: docker-registry.hq.local/dev/asis-web/reverse_proxy
    ports:
      - "443:443"
      - "80:80"

  reverse_proxy_git:
    image: docker-registry.hq.local/dev/asis-web/reverse_proxy
    volumes:
      - ./nginx_local_git.conf:/etc/nginx/conf.d/default.conf
      - /Users/arun/projects/WEBART:/www/data
    ports:
      - "443:443"
      - "80:80"
      - "7999:7999"
